import argparse
import sys
from pathlib import Path

from setup_course_github.config import CONFIG_PATH

CONFIG_TEMPLATE = """\
# course-setup configuration file
# Generated by `setup-course-config`

[github]
# Your GitHub personal access token.
# Needs: repo (read/write), delete_repo (if using retire-course)
# Alternatively, set the GITHUB_TOKEN environment variable.
token = "ghp_YOUR_TOKEN_HERE"

[paths]
# Directory where retired course repos are archived.
# Example: "/Users/yourname/Courses/Archive"
archive = "/path/to/your/archive"

# Optional: path or URL to a custom README.md for new courses.
# If not set, the bundled default README is used.
# Examples:
#   readme_source = "/Users/yourname/templates/README.md"
#   readme_source = "https://example.com/my-readme.md"
# readme_source = ""

[defaults]
# Default notebook type when running setup-course.
# Options: "jupyter" or "marimo"
notebook_type = "jupyter"

# Whether to show verbose output by default.
# Can be overridden with -v / --verbose on the command line.
# verbose = false

# [extras]
# Define custom dependency groups for --extras.
# These merge with built-in groups (python, data, viz, geo, db, ml).
# A custom group with the same name as a built-in group overrides it.
# Example:
# finance = ["yfinance", "pandas-datareader"]
# nlp = ["spacy", "nltk"]
"""


class ConfigExistsError(Exception):
    pass


def create_config(path: Path = CONFIG_PATH, force: bool = False) -> None:
    if path.exists() and not force:
        raise ConfigExistsError(
            f"Config file already exists: {path}\nUse --force to overwrite."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CONFIG_TEMPLATE)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Create a starter config file for course-setup."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing config file.",
    )
    args = parser.parse_args(argv)

    try:
        create_config(CONFIG_PATH, force=args.force)
    except ConfigExistsError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Config file created: {CONFIG_PATH}")
    print("Edit it to set your GitHub token and archive path.")
